name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check out the repo
        uses: actions/checkout@v2
      - name: build version
        uses: benjlevesque/short-sha@v1.2
        id: shortsha
        with:
          length: 7
      - name: log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64
      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container
      - name: build and push docker images
        uses: docker/build-push-action@v2
        with:
          build-args: MYNAMON_VERSION=${{ steps.shortsha.outputs.sha }}
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/mynamon:latest
      - name: create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: latest

